#!/usr/bin/env bash
# Build the real training image (on a CPU base) and run it the way SageMaker
# runs a training job: channels mounted read-only at /opt/ml/input/data/<name>,
# /opt/ml/checkpoints and /opt/ml/output writable, the state machine's exact
# entrypoint + arguments, and the config baked into the image (smoke.yml,
# unchanged). Then a second run on the same checkpoint dir, as after a spot
# interruption. No AWS needed — this is what the "Container test" workflow runs.
#
#   bash tests/sagemaker/container_test.sh [work-dir]
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

WORK="${1:-$(mktemp -d)}"
WORK="$(cd "$WORK" && pwd)"
IMAGE=forgery-train:container-test
echo "[container-test] work dir: $WORK"

docker build -q -f tests/sagemaker/cpu-base.Dockerfile -t forgery-cpu-base tests/sagemaker
docker build -f sagemaker/Dockerfile --build-arg BASE_IMAGE=forgery-cpu-base \
  --build-arg GIT_SHA="$(git rev-parse HEAD 2>/dev/null || echo local)" -t "$IMAGE" .

# created here, not by the (root) container, so the host can write the logs
mkdir -p "$WORK/checkpoints" "$WORK/output"

# synthetic MDS + random-init backbone, generated by the image's own libraries
docker run --rm --entrypoint python -v "$PWD:/repo:ro" -v "$WORK:/work" "$IMAGE" \
  /repo/tests/sagemaker/emulate_training_job.py prepare --root /work

run_job () {                         # end-epoch  log-name
  set +e
  docker run --rm --shm-size=2g \
    -e TRAINING_IMAGE="$IMAGE" \
    -v "$WORK/input/data/train:/opt/ml/input/data/train:ro" \
    -v "$WORK/input/data/test:/opt/ml/input/data/test:ro" \
    -v "$WORK/input/data/artifacts:/opt/ml/input/data/artifacts:ro" \
    -v "$WORK/checkpoints:/opt/ml/checkpoints" \
    -v "$WORK/output:/opt/ml/output" \
    --entrypoint python "$IMAGE" \
    /opt/ml/code/sagemaker/train.py --config config/smoke.yml --end-epoch "$1" train \
    2>&1 | tee "$WORK/output/$2"
  local rc=${PIPESTATUS[0]}
  set -e
  return "$rc"
}

rc=0; run_job 1 run1.log || rc=$?
python3 tests/sagemaker/emulate_training_job.py check --root "$WORK" --log "$WORK/output/run1.log" \
  --returncode "$rc" --end-epoch 1

rc=0; run_job 2 run2.log || rc=$?
python3 tests/sagemaker/emulate_training_job.py check --root "$WORK" --log "$WORK/output/run2.log" \
  --returncode "$rc" --end-epoch 2 --expect-resume

echo "[container-test] PASSED"
